### ISSUE TITLE
Missing Responsible Vulnerability Disclosure

### ISSUE THREAD

**Issue by miglen** [SecurityBSidesBG/BSidesBG-2022-Talks#1]
Mine seems to be missing I guess you didn't have the PDF, here is the file I used to present: https://drive.google.com/file/d/1w1l7GKyhq-sSB3gmAGVyehOVYRwIzJ5R/view?usp=sharing

**Comment by presianbg** [comment]
Yep, I missed that one. Sorry. 
https://github.com/SecurityBSidesBG/BSidesBG-2022-Talks/commit/140efc5f182dd4a1ea3f53c5aee33b833b9d890c
